### ISSUE TITLE
Release Timeline for "Generating Custom Data" Code

### ISSUE THREAD

**Issue by yilin404** [maximiliangilles/MetaGraspNet#17]
Hello,

I hope you're doing well. I was wondering if there is an estimated timeline for the release of the code related to the "Generating Custom Data" section mentioned in the documentation. This feature would be really helpful for my current project, and I am looking forward to testing it out.

Thank you for your hard work and contributions!

**Comment by maximiliangilles** [comment]
Hi @yilin404,

Unfortunately, I am unable to provide a specific timeline at this point. Our current codebase is not yet compatible with the updated Isaac Sim API due to several breaking changes introduced by NVIDIA. We are actively working on resolving these issues, but as a research institute, we have limited time and personnel resources, so progress can be slow sometimes.

Best,

Maximilian
